services:
  db:
    image: postgres:13
    hostname: db.blog.test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
      POSTGRES_HOST: db.blog.test
      POSTGRES_PORT: 5432
  # sidekiq:
  #   build: .
  #   command: bundle exec sidekiq
  #   volumes:
  #     - .:/myapp
  #   depends_on:
  #     - db
  #     - redis

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge  