version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  app:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  # sidekiq:
  #   build: .
  #   command: bundle exec sidekiq
  #   volumes:
  #     - .:/myapp
  #   depends_on:
  #     - db
  #     - redis

volumes:
  pgdata: